import { test, after } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { prisma } from "../../lib/db";
import { readPlanner, writePlanner, clearPlanner, PlannerConflict } from "../../lib/planner-service";

if (!process.env.DATABASE_URL?.includes("timebox_test")) throw new Error("Use a dedicated database named timebox_test");
const users: string[] = [];
after(async () => { await prisma.user.deleteMany({ where: { id: { in: users } } }); await prisma.$disconnect(); });

test("two accounts remain isolated; task identity, ordering, timestamps, conflict rollback and deletion", async () => {
  const a = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  const b = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  users.push(a.id, b.id);
  const date = "2026-09-16";
  const t1 = { id: randomUUID(), title: "A private task", timeSpan: 60, isBig3: true };
  const t2 = { ...t1, id: randomUUID(), title: "Second task", isBig3: false };
  const data = { tasks: [t1, t2], todayTime: { notes: "Private notes" } };
  assert.equal(await writePlanner(a.id, date, data, 0), 1);
  const created = await prisma.task.findUniqueOrThrow({ where: { id: t1.id } });
  assert.deepEqual(await readPlanner(b.id, date), { data: null, revision: 0 });
  const bt = { ...t1, id: randomUUID(), title: "B private task" };
  await writePlanner(b.id, date, { tasks: [bt], todayTime: {} }, 0);
  assert.equal((await readPlanner(a.id, date)).data?.tasks[0].title, "A private task");
  await assert.rejects(writePlanner(b.id, date, data, 1), PlannerConflict);
  assert.equal((await readPlanner(b.id, date)).revision, 1);
  assert.equal((await readPlanner(b.id, date)).data?.tasks[0].id, bt.id);
  await writePlanner(a.id, date, { ...data, tasks: [t2, { ...t1, title: "Updated" }] }, 1);
  const updated = await prisma.task.findUniqueOrThrow({ where: { id: t1.id } });
  assert.equal(updated.createdAt.getTime(), created.createdAt.getTime());
  assert.equal((await readPlanner(a.id, date)).data?.tasks[0].id, t2.id);
  await assert.rejects(writePlanner(a.id, date, data, 1), PlannerConflict);
  const competing = await Promise.allSettled([
    writePlanner(a.id, date, data, 2), writePlanner(a.id, date, data, 2),
  ]);
  assert.equal(competing.filter((result) => result.status === "fulfilled").length, 1);
  await assert.rejects(clearPlanner(a.id, date, 2), PlannerConflict);
  await clearPlanner(a.id, date, 3);
  assert.equal((await readPlanner(a.id, date)).data?.tasks.length, 0);
  assert.equal((await readPlanner(b.id, date)).data?.tasks[0].id, bt.id);
  await assert.rejects(writePlanner(a.id, date, data, 0), PlannerConflict);
});

const base = process.env.TEST_BASE_URL;
test("HTTP auth, CSRF, validation, private cache and session invalidation", { skip: !base }, async () => {
  const user = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  users.push(user.id);
  const token = randomUUID();
  await prisma.session.create({ data: { userId: user.id, sessionToken: token, expires: new Date(Date.now() + 60000) } });
  const cookie = `authjs.session-token=${token}`;
  const url = `${base}/api/planner?date=2026-09-17`;
  for (const method of ["GET", "POST", "DELETE"]) assert.equal((await fetch(url, { method })).status, 401);
  const privateRead = await fetch(url, { headers: { cookie } });
  assert.equal(privateRead.status, 200);
  assert.match(privateRead.headers.get("cache-control")!, /no-store/);
  assert.equal((await fetch(`${base}/api/planner?date=2026-02-30`, { headers: { cookie } })).status, 400);
  const payload = { ownerId: user.id, date: "2026-09-17", revision: 0, data: { tasks: [], todayTime: {} } };
  const headers = { cookie, origin: base!, "Content-Type": "application/json" };
  assert.equal((await fetch(url, { method: "POST", headers: { ...headers, origin: "https://evil.example" }, body: JSON.stringify(payload) })).status, 403);
  assert.equal((await fetch(url, { method: "POST", headers, body: "{" })).status, 400);
  assert.equal((await fetch(url, { method: "POST", headers, body: JSON.stringify({ ...payload, ownerId: "previous-account" }) })).status, 409);
  assert.equal((await fetch(url, { method: "POST", headers, body: JSON.stringify(payload) })).status, 200);
  assert.equal((await fetch(url, { method: "POST", headers, body: JSON.stringify(payload) })).status, 409);
  assert.equal((await fetch(`${url}&revision=1&ownerId=${user.id}`, { method: "DELETE", headers })).status, 200);
  await prisma.session.delete({ where: { sessionToken: token } });
  assert.equal((await fetch(url, { headers: { cookie } })).status, 401);
  const home = await fetch(`${base}/`, { redirect: "manual" });
  assert.equal(home.status, 307);
  assert.equal(home.headers.get("location"), "/login");
});

test("completion, notes and reflection survive saves; moves atomically preserve identity and protect both days", async () => {
  const { moveTaskToNextDay, PlannerMoveError } = await import("../../lib/planner-service");
  const { readDashboard } = await import("../../lib/dashboard-service");
  const a = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  const b = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  users.push(a.id, b.id);
  const date = "2026-12-31", next = "2027-01-01";
  const task = { id: randomUUID(), title: "Move me", timeSpan: 15, isBig3: true, completed: false, scheduledTime: { startHour: 0, startMinute: 15 } };
  const done = { ...task, id: randomUUID(), title: "Done", completed: true };
  await writePlanner(a.id, date, { tasks: [task, done], todayTime: { notes: "keep notes", reflection: "keep reflection" } }, 0);
  const created = await prisma.task.findUniqueOrThrow({ where: { id: task.id } });
  await writePlanner(a.id, next, { tasks: [{ ...task, id: randomUUID(), title: "Existing target" }], todayTime: { notes: "target notes" } }, 0);
  await assert.rejects(moveTaskToNextDay(b.id, date, task.id, 1), PlannerConflict);
  await assert.rejects(moveTaskToNextDay(a.id, date, done.id, 1), PlannerMoveError);
  assert.deepEqual(await moveTaskToNextDay(a.id, date, task.id, 1), { revision: 2, targetDate: next });
  const source = await readPlanner(a.id, date);
  assert.equal(source.data?.tasks.length, 1);
  assert.equal(source.data?.tasks[0].completed, true);
  assert.equal(source.data?.todayTime.reflection, "keep reflection");
  assert.equal(source.data?.todayTime.notes, "keep notes");
  const target = await readPlanner(a.id, next);
  assert.equal(target.revision, 2);
  assert.equal(target.data?.tasks[1].id, task.id);
  assert.equal(target.data?.tasks[1].isBig3, false);
  assert.equal(target.data?.tasks[1].scheduledTime, undefined);
  assert.equal(target.data?.todayTime.notes, "target notes");
  assert.equal((await prisma.task.findUniqueOrThrow({ where: { id: task.id } })).createdAt.getTime(), created.createdAt.getTime());
  await assert.rejects(moveTaskToNextDay(a.id, date, task.id, 1), PlannerConflict);
  await assert.rejects(writePlanner(a.id, next, { tasks: [], todayTime: {} }, 1), PlannerConflict);
  const dashboard = await readDashboard(a.id, next);
  assert.equal(dashboard.today.tasks.length, 2);
  assert.equal(dashboard.days.find((day) => day.date === date)?.completed, 1);
  assert.equal(dashboard.overdueCount, 0);
  assert.equal((await readDashboard(b.id, next)).today.tasks.length, 0);
  assert.equal((await readDashboard(b.id, next)).days.reduce((sum, day) => sum + day.total, 0), 0);
});

test("moving into a full day rolls back the source and target revisions", async () => {
  const { moveTaskToNextDay, PlannerMoveError } = await import("../../lib/planner-service");
  const user = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  users.push(user.id);
  const source = await prisma.planner.create({ data: { userId: user.id, date: "2026-10-01", revision: 1 } });
  const target = await prisma.planner.create({ data: { userId: user.id, date: "2026-10-02", revision: 1 } });
  const task = await prisma.task.create({ data: { plannerId: source.id, title: "stay here" } });
  await prisma.task.createMany({ data: Array.from({ length: 500 }, (_, position) => ({ plannerId: target.id, position })) });
  await assert.rejects(moveTaskToNextDay(user.id, "2026-10-01", task.id, 1), PlannerMoveError);
  assert.equal((await readPlanner(user.id, "2026-10-01")).revision, 1);
  assert.equal((await readPlanner(user.id, "2026-10-02")).revision, 1);
  assert.equal((await prisma.task.findUniqueOrThrow({ where: { id: task.id } })).plannerId, source.id);
});

test("HTTP dashboard and move enforce auth, owner, origin, validation and stale revisions", { skip: !base }, async () => {
  const user = await prisma.user.create({ data: { email: `${randomUUID()}@example.com` } });
  users.push(user.id);
  const token = randomUUID();
  await prisma.session.create({ data: { userId: user.id, sessionToken: token, expires: new Date(Date.now() + 60000) } });
  const cookie = `authjs.session-token=${token}`;
  const headers = { cookie, origin: base!, "Content-Type": "application/json" };
  const task = { id: randomUUID(), title: "HTTP task", timeSpan: 30, isBig3: false, completed: false };
  await writePlanner(user.id, "2026-09-16", { tasks: [task], todayTime: {} }, 0);
  const moveUrl = `${base}/api/planner/move`;
  const payload = { ownerId: user.id, date: "2026-09-16", taskId: task.id, revision: 1 };
  const move = (body: unknown, requestHeaders = headers) => fetch(moveUrl, { method: "POST", headers: requestHeaders, body: JSON.stringify(body) });
  assert.equal((await fetch(`${base}/api/dashboard?date=2026-09-16`)).status, 401);
  assert.equal((await fetch(moveUrl, { method: "POST" })).status, 401);
  assert.equal((await fetch(`${base}/api/dashboard?date=2026-02-30`, { headers })).status, 400);
  const dashboard = await fetch(`${base}/api/dashboard?date=2026-09-16`, { headers });
  assert.equal(dashboard.status, 200);
  assert.match(dashboard.headers.get("cache-control")!, /no-store/);
  assert.equal((await dashboard.json()).today.tasks[0].id, task.id);
  assert.equal((await move(payload, { ...headers, origin: "https://evil.example" })).status, 403);
  assert.equal((await move({ ...payload, ownerId: "different-user" })).status, 409);
  assert.equal((await move({ ...payload, date: "9999-12-31" })).status, 400);
  assert.equal((await move({ ...payload, taskId: "x".repeat(5000) })).status, 413);
  assert.equal((await move(payload)).status, 200);
  assert.equal((await move(payload)).status, 409);
  const next = await fetch(`${base}/api/dashboard?date=2026-09-17`, { headers });
  assert.equal((await next.json()).today.tasks[0].id, task.id);
  const legacy = await fetch(`${base}/?date=2026-09-16`, { headers, redirect: "manual" });
  assert.equal(legacy.status, 307);
  assert.equal(legacy.headers.get("location"), "/planner?date=2026-09-16");
});
